<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bsl</string>
		<string>os</string>
	</array>
	<key>name</key>
	<string>1C</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(//.*\n)</string>
			<key>name</key>
			<string>comment.line.double-slash.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>("[^"]*")</string>
			<key>name</key>
			<string>string.quoted.double.bsl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.interpolated.bsl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string></string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.bsl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(Процедура|Функция)\s+([a-zа-я0-9_]+)\s*\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bsl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.bsl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Proc and function defenition</string>
			<key>end</key>
			<string>(?i:\)\s+(Экспорт)?)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.bsl</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\bЗнач\b)</string>
					<key>name</key>
					<string>storage.modifier.bsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((?&lt;==)(?i)[a-zа-я0-9_]*)\b</string>
					<key>name</key>
					<string>invalid.illegal.bsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((?&lt;== )(?i)[a-zа-я0-9_]*)\b</string>
					<key>name</key>
					<string>invalid.illegal.bsl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:[a-zа-я0-9_]+)</string>
					<key>name</key>
					<string>variable.parameter.bsl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Неопределено|Истина|Ложь|NULL)\b)</string>
			<key>name</key>
			<string>constant.language.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((\h{8}-(\h{4}-){3}\h{12})|\d+\.?\d*)\b</string>
			<key>name</key>
			<string>constant.numeric.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'.+\'</string>
			<key>name</key>
			<string>constant.other.date.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(КонецПроцедуры|КонецФункции)\b)</string>
			<key>name</key>
			<string>storage.type.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#Использовать\b</string>
			<key>name</key>
			<string>keyword.control.import.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Прервать|Продолжить|Возврат)\b)</string>
			<key>name</key>
			<string>keyword.control.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Если|Иначе|ИначеЕсли|Тогда|КонецЕсли)\b)</string>
			<key>name</key>
			<string>keyword.control.conditional.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Попытка|Исключение|КонецПопытки|ВызватьИсключение)\b)</string>
			<key>name</key>
			<string>keyword.control.exception.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Пока|Для (Каждого)?|Из|По|Цикл|КонецЦикла)\b)</string>
			<key>name</key>
			<string>keyword.control.repeat.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(НЕ|И|ИЛИ)\b)</string>
			<key>name</key>
			<string>keyword.operator.logical.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;=|&gt;=|=|&lt;|&gt;</string>
			<key>name</key>
			<string>keyword.operator.comparison.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(=)</string>
			<key>name</key>
			<string>keyword.operator.assignment.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\+|-|\*|/|%)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.bsl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(,|;|\?)|(?i:(\b(Перем|Новый)\b))</string>
			<key>name</key>
			<string>keyword.operator.bsl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.bsl</string>
	<key>uuid</key>
	<string>cf0633ff-beee-424a-a2f7-3dce4093e139</string>
</dict>
</plist>
